import React from 'react';
import { UserProfile } from '../types';
import { UI_CLASSES, SYSTEM_DISCLAIMER } from '../constants';

interface PDFExportProps {
  data: any;
  user: UserProfile;
  type: 'DIAGNOSIS' | 'REPORT';
}

const PDFExport: React.FC<PDFExportProps> = ({ data, user, type }) => {
  const handleExport = () => {
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;

    const date = new Date().toLocaleDateString();
    
    let content = `
      <html>
      <head>
        <title>DocAi Health Summary - ${date}</title>
        <style>
          body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; color: #1A1A1A; background: white; padding: 40px; }
          .header { border-bottom: 2px solid #1A1A1A; padding-bottom: 20px; margin-bottom: 40px; }
          .title { font-size: 24px; font-weight: bold; text-transform: uppercase; letter-spacing: 0.1em; }
          .section { margin-bottom: 30px; }
          .section-title { font-size: 10px; font-weight: bold; text-transform: uppercase; letter-spacing: 0.2em; color: #6B705C; margin-bottom: 10px; }
          .grid { display: grid; grid-template-cols: 1fr 1fr; gap: 20px; font-size: 12px; }
          table { width: 100%; border-collapse: collapse; margin-top: 10px; }
          th, td { border: 1px solid #E5E5E5; padding: 12px; text-align: left; font-size: 11px; }
          th { background: #F9F9F9; font-weight: bold; color: #666; }
          .disclaimer { font-size: 9px; margin-top: 60px; text-align: center; text-transform: uppercase; color: #999; border-top: 1px solid #EEE; padding-top: 20px; letter-spacing: 0.05em; }
          .footer { margin-top: 40px; font-size: 10px; opacity: 0.5; }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="title">DocAi Clinical Analysis Report</div>
          <div class="footer">Generated by DocAi Health Systems on ${date}</div>
        </div>

        <div class="section">
          <div class="section-title">Patient Profile</div>
          <div class="grid">
            <div><strong>Name:</strong> ${user.name}</div>
            <div><strong>Email:</strong> ${user.email}</div>
            <div><strong>Age:</strong> ${user.age || 'N/A'}</div>
            <div><strong>Gender:</strong> ${user.gender || 'N/A'}</div>
          </div>
        </div>
    `;

    if (type === 'DIAGNOSIS') {
      content += `
        <div class="section">
          <div class="section-title">Diagnostic Findings</div>
          <div class="grid">
            <div><strong>Condition:</strong> ${data.disease}</div>
            <div><strong>Clinical Confidence:</strong> ${data.probability}%</div>
            <div><strong>Severity Index:</strong> ${data.severity}</div>
          </div>
          <div style="margin-top: 20px; font-size: 12px; line-height: 1.6;">
            <strong>Medical Interpretation:</strong><br/>
            ${data.explanation}
          </div>
          <div style="margin-top: 20px; font-size: 12px;">
            <strong>Recommended Actions:</strong>
            <ul style="padding-left: 20px;">${data.recommendations.map((r:string) => `<li>${r}</li>`).join('')}</ul>
          </div>
        </div>
      `;
    } else {
      content += `
        <div class="section">
          <div class="section-title">Laboratory Biomarker Analysis</div>
          <div style="margin-bottom: 20px; font-size: 12px; line-height: 1.6;">${data.summary}</div>
          <table>
            <thead>
              <tr><th>Biomarker</th><th>Detected Value</th><th>Clinical Status</th></tr>
            </thead>
            <tbody>
              ${data.markers.map((m:any) => `<tr><td><strong>${m.name}</strong></td><td>${m.value}</td><td>${m.status}</td></tr>`).join('')}
            </tbody>
          </table>
          <div style="margin-top: 20px; font-size: 12px; line-height: 1.6;">
            <strong>AI Guidance:</strong><br/>
            ${data.advice}
          </div>
        </div>
      `;
    }

    content += `
        <div class="disclaimer">${SYSTEM_DISCLAIMER}</div>
        <script>window.print();</script>
      </body>
      </html>
    `;

    printWindow.document.write(content);
    printWindow.document.close();
  };

  return (
    <button 
      onClick={handleExport}
      className={`${UI_CLASSES.button} flex-1 shadow-lg shadow-black/5`}
    >
      Export Clinical PDF
    </button>
  );
};

export default PDFExport;